"""Embed a pixel-exact, metadata-free lossless WebP sample using Pillow."""

import argparse
import base64
import io
from pathlib import Path

from PIL import Image

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("source", type=Path)
args = parser.parse_args()
with Image.open(args.source) as original:
    image = original.convert("RGBA")
    encoded = io.BytesIO()
    image.save(encoded, format="WEBP", lossless=True, method=6, exact=True)
    payload = encoded.getvalue()
    with Image.open(io.BytesIO(payload)) as optimized:
        if optimized.convert("RGBA").tobytes() != image.tobytes():
            raise RuntimeError("Sample optimization changed image pixels")
output = Path(__file__).resolve().parents[1] / "dist" / "sample.js"
output.write_text(
    '// Generated by scripts/optimize-sample.py: lossless WebP.\n'
    f'window.EMOTE_SAMPLE="{base64.b64encode(payload).decode("ascii")}";\n',
    encoding="utf-8",
)
print(f"Embedded {image.width}x{image.height} lossless WebP: {len(payload):,} bytes")
